vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        cake_file:
            uri_prefix: /uploads/cakes
            upload_destination: '%kernel.project_dir%/public/uploads/cakes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
